export const BRIDGE = 'https://bridge.walletconnect.org';
export const ALGOD_HOST_MAIN = 'https://node.algoexplorerapi.io';
export const ALGOD_HOST_TEST = 'https://node.testnet.algoexplorerapi.io';
export const INDEXER_HOST_MAIN = 'https://algoindexer.algoexplorerapi.io/';
export const INDEXER_HOST_TEST =
  'https://algoindexer.testnet.algoexplorerapi.io/';
export const PRICE = 2;
export const ASSET_INDEX = 80865821;
export const ARTIST_MAIN_ADDRESS =
  'PIQVKPN4EAHMS74DK5CSCIZCJ6CM7OSIUZYQ5Y6MYFP26XZHBPRNJHAPDA';
export const ARTIST_SOUND_ADDRESS =
  'E6U45JTJJQKGIQXECBTUAEARHU7PKCSRVLR5Q4PWT2EDG5XSOVOMK77LUA';
export const CONTRACT_RESULT =
  'BiAGAQTnhsgmAAMFJgEgeiFVPbwgDsl/g1dFISMiT4TPukimcQ7jzMFfr18nC+IxATIADjEGMgMSEDEgMgMSEDIEIQQSQADXMgQhBRJAAAEAMgQhBRIzABAiEhAzAAiBgJX1KhIQMwAHKBIQMwAJMgMSEDMBECMSEDMBEiUSEDMBADMAABIQMwEAMwEUEhAzARUyAxIQMwERJBIQMwIQIxIQMwISIhIQMwIUMwEAEhAzAhUzAQASEDMCESQSEDMDECISEDMDCCUSEDMDBygSEDMDCSgSEDMDADMCABIQMwQQIhIQMwQIgYCt4gQSEDMEB4AgJ6nOpmlMFGRC5BBnQBARPT71ClGq49hx9p6IM3bydVwSEDMECTIDEhBCANwyBCEEEjMAECISEDMACIGgwh4SEDMAACgSEDMACTIDEhAzARAjEhAzARIlEhAzAQAzAAcSEDMBADMBFBIQMwEVMgMSEDMBESQSEDMCECMSEDMCEiISEDMCACgSEDMCFDMBABIQMwIVMgMSEDMCESQSEDIEIQQSMwAQIxIQMwASJRIQMwAAMwAUEhAzABUyAxIQMwARJBIQMwAUKBIQMwEQIxIQMwESIhIQMwERJBIQMwEUKBIQMwEVKBIQMwIQIhIQMwIIJRIQMwIAMwEAEhAzAgcoEhAzAgkoEhAREEM=';
export const IS_MAIN_NET = false;
export const FIREBASE_ID = 'mushroom-cloud-api';
